export const PRICING_TIERS = {
  free: {
    id: "free",
    name: "Free Trial",
    price: 0.00,
    currency: "£",
    period: "14 days",
    description: "Perfect for trying out NexaraX",
    popular: false,
    cta: "Start Free Trial",
    features: {
      aiPosts: 5,
      aiVideos: 0,
      platforms: 1,
      templates: "Basic templates",
      analytics: "Basic analytics",
      support: "Community support",
      trialDays: 14,
      rollsIntoStarter: true,
    },
  },
  starter: {
    id: "starter",
    name: "Starter",
    price: 9.99,
    currency: "£",
    period: "month",
    description: "Great for individual creators",
    popular: false,
    cta: "Choose Starter",
    features: {
      aiPosts: 50,
      aiVideos: 10,
      platforms: 2,
      templates: "Premium templates",
      analytics: "Basic analytics",
      support: "Email support",
      emailNotifications: true,
    },
  },
  pro: {
    id: "pro",
    name: "Pro",
    price: 29.99,
    currency: "£",
    period: "month",
    description: "Perfect for growing businesses",
    popular: true,
    cta: "Choose Pro",
    features: {
      aiPosts: 200,
      aiVideos: 50,
      platforms: 3,
      templates: "All templates",
      voiceCloning: true,
      analytics: "Advanced analytics",
      support: "Priority support",
    },
  },
  enterprise: {
    id: "enterprise",
    name: "Enterprise",
    price: 299.00,
    currency: "£",
    period: "month",
    description: "For large teams and agencies",
    popular: false,
    cta: "Choose Enterprise",
    features: {
      aiPosts: "unlimited",
      aiVideos: "unlimited",
      platforms: "unlimited",
      templates: "Custom templates",
      whiteLabel: true,
      apiAccess: true,
      support: "Dedicated support",
      fairUsage: true,
    },
  },
} as const

export type PricingTier = keyof typeof PRICING_TIERS
